name: 'Jest PR Code Coverage '
description: 'Run test and report coverage on a pull request using Jest'
author: 'Khalid Elshafie'
branding:
  color: purple
  icon: activity

inputs:
  github-token:
    description: 'Github access token'
    required: false
    default: ${{ github.token }}
  test-script:
    description: 'Script used to run the tests'
    required: false
    default: npx jest
  min-threshold:
    description: Specify a minimum coverage threshold percentage.
    required: false

runs:
  using: node16
  main: dist/index.js
