name: 'Jest PR Code Coverage '
description: 'Run test and report coverage on a pull request using Jest'
author: 'Khalid Elshafie'

inputs:
  github-token:
    description: 'Github access token'
    required: false
    default: ${{ github.token }}

runs:
  using: node16
  main: dist/index.js
